spring.profiles.active: dev
spring.pidfile: shared/tmp/pids/application.pid
spring.cloud.config.server.git.uri: http://git.rfdoa.cn/wujianweia/test-pixiu-config.git
server.port: 9001

---
spring:
  profiles: dev
  
---
spring:
  profiles: test
  
---
spring:
  profiles: production